/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.sql.*;
import java.awt.*;
import java.awt.AWTEvent.*;
import java.util.*;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author DELL
 */
public class Employee extends javax.swing.JFrame {
 Connection conn        =       null;
    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSecondName = new javax.swing.JTextField();
        txtMobileNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaAddressForCommunication = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtPANNumber = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtAadharNumber = new javax.swing.JTextField();
        EmpId = new javax.swing.JLabel();
        txtEmpId = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtCreateNewEmployee = new javax.swing.JButton();
        jbtDeleteEmployee = new javax.swing.JButton();
        jbtEditExistingEmployee = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbtViewEmployeeDetails = new javax.swing.JButton();
        jbtExit = new javax.swing.JButton();
        jbtClear = new javax.swing.JButton();
        jMessage = new javax.swing.JOptionPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(" Employee Details");

        jLabel2.setText("First Name");

        jLabel3.setText("Second Name");

        txtSecondName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecondNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Mobile Number");

        jLabel5.setText("Address For Communication");

        jTxtAreaAddressForCommunication.setColumns(20);
        jTxtAreaAddressForCommunication.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaAddressForCommunication);

        jLabel6.setText("PAN Number");

        jLabel7.setText("Aadhar Number");

        EmpId.setText("Emp Id");

        jbtCreateNewEmployee.setText("Create New Employee");
        jbtCreateNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCreateNewEmployeeActionPerformed(evt);
            }
        });

        jbtDeleteEmployee.setText("Delete An Employee");
        jbtDeleteEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDeleteEmployeeActionPerformed(evt);
            }
        });

        jbtEditExistingEmployee.setText("Edit Existing Employee Details");
        jbtEditExistingEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtEditExistingEmployeeActionPerformed(evt);
            }
        });

        jButton4.setText("Edit Existing Employee Details");

        jbtViewEmployeeDetails.setText("View Employee Details");
        jbtViewEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtViewEmployeeDetailsActionPerformed(evt);
            }
        });

        jbtExit.setText("Exit");
        jbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExitActionPerformed(evt);
            }
        });

        jbtClear.setText("Clear Details");
        jbtClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtEditExistingEmployee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtCreateNewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbtExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtClear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtViewEmployeeDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                .addComponent(jbtDeleteEmployee, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jbtCreateNewEmployee)
                .addGap(32, 32, 32)
                .addComponent(jbtEditExistingEmployee)
                .addGap(35, 35, 35)
                .addComponent(jbtDeleteEmployee)
                .addGap(48, 48, 48)
                .addComponent(jbtViewEmployeeDetails)
                .addGap(42, 42, 42)
                .addComponent(jbtClear)
                .addGap(37, 37, 37)
                .addComponent(jbtExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(249, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAadharNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addComponent(txtPANNumber, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEmpId, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMobileNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addComponent(txtSecondName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(EmpId))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpId)
                    .addComponent(txtEmpId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSecondName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPANNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtAadharNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSecondNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecondNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecondNameActionPerformed

    public void createConnection()
    {
       
       
       
       
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/demo","root","dharsan");
          
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    
            
        
    }
    private void jbtCreateNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCreateNewEmployeeActionPerformed
        //create a new Employee record for table EMPLOYEE from the form details
        String empID            =       txtEmpId.getText();
        String firstName        =       txtFirstName.getText();
        String secondName       =       txtSecondName.getText();
        String mobileNumber     =       txtMobileNumber.getText();
        String address          =       jTxtAreaAddressForCommunication.getText();
        String panNumber        =       txtPANNumber.getText();
        String aadharNumber     =       txtAadharNumber.getText();
        int empid               =       Integer.parseInt(empID);
        
            //call createConnection method
             createConnection();
             
            //insert query
             PreparedStatement pInsertStmt=null;
              //ResultSet rs=null;
        
              try
              {
                 
                  pInsertStmt       =       conn.prepareStatement("INSERT INTO EMPLOYEE VALUES(?,?,?,?,?,?,?)");
                  pInsertStmt.setInt(1,empid);
                  pInsertStmt.setString(2,firstName);
                  pInsertStmt.setString(3,secondName);
                  pInsertStmt.setString(4,mobileNumber);
                  pInsertStmt.setString(5,address); 
                  pInsertStmt.setString(6,panNumber);
                  pInsertStmt.setString(7,aadharNumber);
                  pInsertStmt.executeUpdate();       
                 jMessage.showMessageDialog(jPanel1,"row inserted");
                 
                 //refresh all the text boxes
                  txtEmpId.setText("");
                  txtEmpId.setEnabled(true);
                  txtFirstName.setText("");
                  txtSecondName.setText("");
                  txtMobileNumber.setText("");
                  jTxtAreaAddressForCommunication.setText("");
                  txtPANNumber.setText("");
                  txtAadharNumber.setText("");
              }
              catch(Exception e)
              {
                  e.printStackTrace();
              }
    }//GEN-LAST:event_jbtCreateNewEmployeeActionPerformed

    private void jbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtExitActionPerformed

    private void jbtViewEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtViewEmployeeDetailsActionPerformed
        
            //call createConnection method
             createConnection();
            //insert query
            
              PreparedStatement pInsertStmt     =   null;
              ResultSet rs                      =   null;
              String empID                      =   txtEmpId.getText();
              int empid                         =   Integer.parseInt(empID);
              try
              { 
                  
             pInsertStmt        =       conn.prepareStatement("select * from EMPLOYEE where EMPID=?");
             pInsertStmt.setInt(1,empid);
             pInsertStmt.executeQuery();       
              
               // get resultset
               rs               =       pInsertStmt.executeQuery();
               
               while(rs.next()){
                   
                  int empNo              =      rs.getInt(1);
                  String firstName       =      rs.getString(2);
                  String secondName      =      rs.getString(3);
                  String mobileNumber    =      rs.getString(4);
                  String address         =      rs.getString(5);
                  String panNumber       =      rs.getString(6);
                  String aadharNumber    =      rs.getString(7);
                  
               
                  txtEmpId.setEnabled(false);
                  txtFirstName.setText(firstName);
                  txtSecondName.setText(secondName);
                  txtMobileNumber.setText(mobileNumber);
                  jTxtAreaAddressForCommunication.setText(address);
                  txtPANNumber.setText(panNumber);
                  txtAadharNumber.setText(aadharNumber);
                 
               }
            
              }
              catch(Exception e)
              {
                  e.printStackTrace();
              }
      
        
    }//GEN-LAST:event_jbtViewEmployeeDetailsActionPerformed

    private void jbtEditExistingEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtEditExistingEmployeeActionPerformed
        // TODO add your handling code here:
             String empID           =       txtEmpId.getText();
             String firstName       =       txtFirstName.getText();
             String secondName      =       txtSecondName.getText();
             String mobileNumber    =       txtMobileNumber.getText();
             String address         =       jTxtAreaAddressForCommunication.getText();
             String panNumber       =       txtPANNumber.getText();
             String aadharNumber    =       txtAadharNumber.getText();
            int empid               =       Integer.parseInt(empID);
            //call createConnection method
             createConnection();
             
            //insert query
        
              PreparedStatement pUpdateStmt     =       null;
              //ResultSet rs=null;
        
              try
              { 
                  
             pUpdateStmt            =           conn.prepareStatement("UPDATE EMPLOYEE SET FIRSTNAME=?,LASTNAME=?,MOBILENUMBER=?,ADDRESS=?,PANNUMBER=?,AADHARNUMBER=? WHERE EMPID=?");
             pUpdateStmt.setString(1,firstName);
             pUpdateStmt.setString(2,secondName);
             pUpdateStmt.setString(3,mobileNumber);
             pUpdateStmt.setString(4,address); 
             pUpdateStmt.setString(5,panNumber);
             pUpdateStmt.setString(6,aadharNumber);
             pUpdateStmt.setInt(7,empid);
             pUpdateStmt.executeUpdate();       
             System.out.println("row inserted");
             
             jMessage.showMessageDialog(jPanel1,"row updated");
             txtEmpId.setText("");
             txtEmpId.setEnabled(true);
             txtFirstName.setText("");
             txtSecondName.setText("");
             txtMobileNumber.setText("");
             jTxtAreaAddressForCommunication.setText("");
             txtPANNumber.setText("");
             txtAadharNumber.setText("");
              }
              catch(Exception e)
              {
                  e.printStackTrace();
              }
    }//GEN-LAST:event_jbtEditExistingEmployeeActionPerformed

    private void jbtDeleteEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDeleteEmployeeActionPerformed
        // TODO add your handling code here:
          //call createConnection method
             createConnection();
            //insert query
             //String insertQuery=
              PreparedStatement pDeleteStmt         =       null;
              ResultSet rs                          =       null;
              String empID                          =       txtEmpId.getText();
              int empid                             =       Integer.parseInt(empID);
              try
              { 
                pDeleteStmt             =       conn.prepareStatement("DELETE  FROM EMPLOYEE WHERE EMPID=?");
                pDeleteStmt.setInt(1,empid);
                pDeleteStmt.executeUpdate();       
                System.out.println("row deleted");
             
                jMessage.showMessageDialog(jPanel1,"row deleted");
               // get resultset
                txtEmpId.setText("");
                txtEmpId.setEnabled(true);
                txtFirstName.setText("");
                txtSecondName.setText("");
                txtMobileNumber.setText("");
                jTxtAreaAddressForCommunication.setText("");
                txtPANNumber.setText("");
                txtAadharNumber.setText("");
            
              }
              catch(Exception e)
              {
                  e.printStackTrace();
              }
      
        
    }//GEN-LAST:event_jbtDeleteEmployeeActionPerformed

    private void jbtClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearActionPerformed
        // TODO add your handling code here:
                  txtEmpId.setText("");
                   txtEmpId.setEnabled(true);
                  txtFirstName.setText("");
                  txtSecondName.setText("");
                  txtMobileNumber.setText("");
                  jTxtAreaAddressForCommunication.setText("");
                  txtPANNumber.setText("");
                  txtAadharNumber.setText("");
    }//GEN-LAST:event_jbtClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmpId;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTxtAreaAddressForCommunication;
    private javax.swing.JButton jbtClear;
    private javax.swing.JButton jbtCreateNewEmployee;
    private javax.swing.JButton jbtDeleteEmployee;
    private javax.swing.JButton jbtEditExistingEmployee;
    private javax.swing.JButton jbtExit;
    private javax.swing.JButton jbtViewEmployeeDetails;
    private javax.swing.JTextField txtAadharNumber;
    private javax.swing.JTextField txtEmpId;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtPANNumber;
    private javax.swing.JTextField txtSecondName;
    // End of variables declaration//GEN-END:variables
}
